#!/bin/bash

IP=""
KEY_NAME=""
PROJECT_NAME=""

echo 'Hash-busting index.html'
./scripts/rewriteIndex

echo 'Syncing files to server'
rsync --exclude=node_modules/ -rave "ssh -i ~/.ssh/${KEY_NAME} -A" * root@${IP}:${PROJECT_NAME};

echo 'SSHing in and restarting the server'
ssh root@${IP} -i ~/.ssh/${KEY_NAME} "cd ${PROJECT_NAME} && npm install && sudo supervisorctl restart ${PROJECT_NAME}"
